version: '3'

services:
  redis:
    image: ${DOCKER_REGISTRY}hedwi/redis:6.0
    restart: always
    container_name: meet_redis
    volumes:
      - ./redis/data:/data/redis
      - ./redis/logs/redis.log:/data/logs/redis.log
      - ./redis/redis.conf:/etc/redis/redis.conf
    command:
      redis-server /etc/redis/redis.conf
    network_mode: "host"

  
  meet-server:
    image: ${DOCKER_REGISTRY}hedwi/hedwi-meetserver:latest
    restart: always
    volumes:
      - ./meetserver/config.yaml:/data/www/hedwi-meetserver/config.yaml
      - ./meetserver/certs:/tmp/hedwi_certs
      - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt
      - /etc/ssl/certs/ca-bundle.trust.crt:/etc/ssl/certs/ca-bundle.trust.crt
    working_dir: /data/www/hedwi-meetserver
    command: ["/data/www/hedwi-meetserver/hedwi-meetserver"]
    network_mode: "host"
    environment:
      DOMAIN: "${DOMAIN}"
      MEET_ADDR: "${HEDWI_MEET_ADDR}"
      REDIS_ADDR: "${REDIS_ADDR}"
      REDIS_USER: "${REDIS_USER}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      HEDWI_MEET_KEY: "${HEDWI_MEET_KEY}"
      HEDWI_MEET_SECRET: "${HEDWI_MEET_SECRET}"
    depends_on:
      - redis


  nginx:   #
    image: ${DOCKER_REGISTRY}hedwi/nginx:1.22  #nginx镜像，如果镜像容器没有会去自动拉取
    container_name: meet_nginx       #容器的名称
    restart: always             #跟随docker的启动而启动
    volumes:                    #挂载卷命令
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/access.log:/var/log/nginx_access.log
      - ./nginx/logs/error.log:/var/log/nginx_error.log
      - ./nginx/conf.d/meet.conf:/etc/nginx/conf.d/default.conf #映射配置文件
      - ./nginx/certs:/etc/nginx/certs:rw

    depends_on:
      - redis
      - meet-server
    network_mode: "host"

volumes:
    redis:
    meet-server:
    nginx:
